import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import HerbCard from '../components/herbs/HerbCard'
import styles from '../styles/Home.module.css'

const herbTraditionContent = 'W medycynie tradycyjnej  uchodził za panaceum. Tradycja stosowania rumianku w ziołolecznictwie sięga czasów najdawniejszych. Starożytni Egipcjanie uważali rumianek za dar Ra, boga Słońca i leczyli za jego pomocą oparzenia słoneczne. Dioskurides w „De Materia Medica” (50-70 r.n.e.) zalecał go jako środek na ból brzucha.'

interface HomeProps {
  title: string, 
}
const Home: NextPage<HomeProps> = ({ title }) => {
  return (
    <div className={styles['app']}>
      <Head>
        <title>HRBZ.org - Encyclopedia herbam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['title']}>HERB.ME</div>
      <div className='home-page-container' style={{ padding: '10px', color: 'darkgreen' } }>
        <Link href='http://localhost:8080/herbs/62a3adfa142940dd012a3a52'>Rumianek pospolity</Link>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
