import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const herbTraditionContent = 'W medycynie tradycyjnej  uchodził za panaceum. Tradycja stosowania rumianku w ziołolecznictwie sięga czasów najdawniejszych. Starożytni Egipcjanie uważali rumianek za dar Ra, boga Słońca i leczyli za jego pomocą oparzenia słoneczne. Dioskurides w „De Materia Medica” (50-70 r.n.e.) zalecał go jako środek na ból brzucha.'

type HomeProps = {
  title: string, 
}
const Home: NextPage<HomeProps> = ({ title }) => {
  return (
    <div className={styles['app']}>
      <Head>
        <title>HRBZ.org - Encyclopedia herbam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['title']}>HERB.ME</div>
      <main className={styles['app-container']}>
        <div className={styles.title}>{title}</div>
        <div className={styles['herb-card-container']}>
          <div className={styles['herb-header-container']}>
            <div className={styles['herb-icon-container']}>
              <img className={styles['herb-icon']} src="/img/chamomile_wiki.jpg" alt="chamomile icon" />
            </div>|
            <div className={styles['herb-name-container']}>
              <div className={styles['herb-name-locale-container']}>RUMIANEK</div>
              <div className={styles['herb-name-latin-container']}>Matricaria chamomilla</div>
            </div>
          </div>
          <div className={styles['herb-tradition-container']}>
            <div className={styles['herb-tradition-content-container']}>
              <div className={styles['herb-tradition-header-container']}>Tradycja</div>
              <div className={styles['herb-tradition-subtext-container']}>
                {herbTraditionContent}  
              </div>
            </div>
            <div className={styles['tradition-icon-container']}>
              <img className={styles['herb-content-icon']} src="/img/sun.jpg" alt='tradition icon' />
            </div>
          </div>
          <div className={styles['herb-effects-container']}>
            <div className={styles['herb-tradition-header-container']}>Działanie</div>
            <div className={styles['herb-tradition-content-container']}>
              <ul>
                <li>Wspomagające trawienie</li>
                <li>Przeciwzapalne</li>
                <li>Nasenne i uspokajające</li>
                <li>Wspomagające gojenie</li>
              </ul>
            </div>
          </div>
          <div className={styles['herbz-sections-spacing']}> </div>
          <div className={styles['herb-effects-container']}>
            <div className={styles['herb-tradition-header-container']}>Dolegliwości</div>
            <div className={styles['herb-tradition-content-container']}>
              <ul>
                <li>Niestrawność</li>
                <li>Infekcje</li>
                <li>Stres</li>
                <li>Lekkie urazy skóry</li>
              </ul>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
